files:
  - source: /resources/lang/44/language_en_US.properties
    translation: /resources/lang/44/language_%locale_with_underscore%.properties
  - source: /resources/assets/the5zigmod/lang/en_US.lang
    translation: /resources/assets/the5zigmod/lang/%locale_with_underscore%.lang
